name: test_env_xwmt
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - gsw
  - netcdf4
  - numba
  - numpy
  - pandas
  - pylint
  - python==3.9
  - pytest
  - xarray
  - pip
  - pip:
    - xgcm @ git+https://github.com/xgcm/xgcm.git@master
    - xhistogram
