name: testing
channels:
  - conda-forge
dependencies:
  - python==3.10
  - black
  - gsw
  - netcdf4
  - nc-time-axis
  - numpy
  - scipy
  - numba
  - pandas
  - pip
  - pylint
  - pytest
  - xarray
  - xhistogram
  - pip:
    - git+https://github.com/xgcm/xgcm.git@7492277de22ed1e677a6a7523b61b20643a98a77
    - git+https://github.com/hdrake/xbudget.git@main
