name: testing
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - gsw
  - netcdf4
  - numba
  - numpy
  - pandas
  - pip
  - pylint
  - python==3.10
  - pytest
  - xarray
  - xgcm==0.8.1
  - xhistogram
  - pip:
    - git+https://github.com/hdrake/xbudget.git
