name: docs_env_xwmt
channels:
  - conda-forge
dependencies:
  - python==3.11
  - black
  - pylint
  - pytest
  - netcdf4
  - nc-time-axis
  - ipython
  - jupyter
  - jupyter-sphinx
  - matplotlib
  - sphinx-book-theme
  - gsw
  - pip
  - pip:
    - git+https://github.com/hdrake/xbudget.git@main
